### ISSUE TITLE
Optimize getty harvester

### ISSUE THREAD

**Issue by coret** [TomDeneire/pictor#1]
The SPARQL query in the Getty harvester can be optimized, that is filter in SPARQL not in Python:
```
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
SELECT ?iiif WHERE {
  ?item crm:P129i_is_subject_of ?iiif .
  FILTER(CONTAINS(STR(?iiif),'iiif/manifest'))
}
```

https://github.com/TomDeneire/pictor/blob/689fb0da8bfe3b47db1eb006feb4c83b9469acea/data/harvester/getty.py#L11

**Comment by TomDeneire** [comment]
You're absolutely right, I'm a real SPARQL noob. Filtering on string values seems hard in SPARQL. Can't get your solution to work, though?

https://vocab.getty.edu/sparql?query=PREFIX+crm%3A+%3Chttp%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2F%3E%0D%0ASELECT+%3Fiiif+WHERE+%7B%0D%0A++%3Fitem+crm%3AP129i_is_subject_of+%3Fiiif+.%0D%0A++FILTER%28CONTAINS%28STR%28%3Fiiif%29%2C%27iiif%2Fmanifest%27%29%29%0D%0A%7D&_implicit=false&implicit=true&_equivalent=false&_form=%2Fsparql

**Comment by coret** [comment]
You're using the wrong endpoint (the right one is in getty.py).

And the web-gui version:
https://data.getty.edu/museum/collection/sparql-ui#query=PREFIX%20crm%3A%20%3Chttp%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2F%3E%0ASELECT%20%3Fiiif%20WHERE%20%7B%0A%20%20%3Fitem%20crm%3AP129i_is_subject_of%20%3Fiiif%20.%0A%20%20FILTER(CONTAINS(STR(%3Fiiif)%2C'iiif%2Fmanifest'))%0A%7D&endpoint=https%3A%2F%2Fdata.getty.edu%2Fmuseum%2Fcollection%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&contentTypeConstruct=application%2Fn-triples%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)

**Comment by TomDeneire** [comment]
Thanks, was working on AAT today, hence the confusion ;-)

**Comment by TomDeneire** [comment]
https://github.com/TomDeneire/pictor/commit/857ebc796e6397c3c917084d7cbefd57a87f59f1
