### ISSUE TITLE
connection error BSB

### ISSUE THREAD

**Issue by TomDeneire** [TomDeneire/pictor#10]
In https://github.com/TomDeneire/pictor/blob/main/data/harvester/bayerische.py pager gets stuck at https://api.digitale-sammlungen.de/iiif/presentation/v2/collection/top?cursor=AoIIP4AAACtic2IxMTU4MDkyNw== 

`HTTPSConnectionPool(host='api.digitale-sammlungen.de', port=443): Max retries exceeded with url: /iiif/presentation/v2/collection/top?cursor=AoIIP4AAACtic2IxMTU4MDkyNw== (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f38ec29e490>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

**Comment by TomDeneire** [comment]
Exact timestamp:

`https://api.digitale-sammlungen.de/iiif/presentation/v2/collection/top?cursor=AoIIP4AAACtic2IxMTQxMTQ4OQ== HTTPSConnectionPool(host='api.digitale-sammlungen.de', port=443): Max retries exceeded with url: /iiif/presentation/v2/collection/top?cursor=AoIIP4AAACtic2IxMTQxMTQ4OQ== (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f02875b0730>: Failed to establish a new connection: [Errno 110] Connection timed out')) 2022-11-10 10:38:25.504730`

**Comment by alexander-winkler** [comment]
On my machine it ran through smoothly (`wc -l > 2805060 ../manifests/bayerische.txt`). I added an `timeout = 10` Parameter to the request.get() .

**Comment by TomDeneire** [comment]
I get more results now (131251), but still it stops:

`https://api.digitale-sammlungen.de/iiif/presentation/v2/collection/top?cursor=AoIIP4AAACtic2IxMTM4NDg0OA== HTTPSConnectionPool(host='api.digitale-sammlungen.de', port=443): Max retries exceeded with url: /iiif/presentation/v2/collection/top?cursor=AoIIP4AAACtic2IxMTM4NDg0OA== (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f82e00cae80>, 'Connection to api.digitale-sammlungen.de timed out. (connect timeout=10)')) 2022-11-10 11:16:40.176157`

Going to set it to `30` and try again.

**Comment by TomDeneire** [comment]
Still the same.

`https://api.digitale-sammlungen.de/iiif/presentation/v2/collection/top?cursor=AoIIP4AAACtic2IxMTM3ODk1OQ== HTTPSConnectionPool(host='api.digitale-sammlungen.de', port=443): Max retries exceeded with url: /iiif/presentation/v2/collection/top?cursor=AoIIP4AAACtic2IxMTM3ODk1OQ== (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f87a68df8b0>, 'Connection to api.digitale-sammlungen.de timed out. (connect timeout=30)')) 2022-11-10 11:26:07.669633`

Can you upload the full `bayerische.txt` @alexander-winkler ?

**Comment by alexander-winkler** [comment]
done (had to upload the *.txt.gz version as `du -h *.txt` > 200M)

**Comment by TomDeneire** [comment]
Great, thanks. I think .gz is the way to go because indeed many files will be too large for GitHub

**Comment by jbaiter** [comment]
So I just had a look at the logs:

- I see a request  for `/iiif/presentation/v2/collection/top?cursor=AoIIP4AAADZic2IxMTM4MDQzMl8wMDYyN191MDAx` at 11:25:37.790, after that only a few single requests for `cursor=AoIIP4AAACtic2IxMTM3ODk1OQ==`, all served correctly as HTTP 200 with an `application/json` payload
- All of these requests were hitting the cache, so should have arrived within a few milliseconds

Actually, *all* of the failing cursors mentioned in this issue should have been served from the cache, which was filled by my initial test crawl after the rollout.
Is there any possibility these timeouts are occurring due to some connectivity issues on your side? I can see absolutely nothing in the application or reverse proxy logs that indicates any problems :-/

**Comment by TomDeneire** [comment]
I think you're right. @alexander-winkler didn't have any issues either. The strange thing is, I'm on a wired university connection here, which seems quite sturdy to me... Oh well, at least we have the manifests now ;-) Thanks.
