### ISSUE TITLE
Universitäts- und Landesbibliothek Düsseldorf

### ISSUE THREAD

**Issue by TomDeneire** [TomDeneire/pictor#15]
Suggestion by Patrick Sahle:

https://digital.ub.uni-duesseldorf.de/ms/oai/?verb=ListSets lead to another bunch of 10 collections that have IIIF manifests. "Universitäts- und Landesbibliothek Düsseldorf" would be the official name

**Comment by alexander-winkler** [comment]
Other libraries using Visual Library should work the same (https://digital.ub.uni-paderborn.de, https://digitale-sammlungen.ulb.uni-bonn.de/ ...). I can check this.

**Comment by TomDeneire** [comment]
That would be great. By the way, I'm converting my todo notes into issues here, so you'll see more of these popping up...
