### ISSUE TITLE
Returning full images rather than thumbnails

### ISSUE THREAD

**Issue by jpadfield** [TomDeneire/pictor#31]
Just had a look with a search for the term "saints" and I noticed that the thumbnails being displayed in the results where actually the full resolution versions of the images - it might be good to parse the URLs and only ask for smaller images?

As an example the URL for one thumbnail was: 
https://media.getty.edu/iiif/image/eca8c2a4-2a7e-4dc9-837c-e1ec3724cce5/full/full/0/default.jpg

But it might be better to have something like:
https://media.getty.edu/iiif/image/eca8c2a4-2a7e-4dc9-837c-e1ec3724cce5/full/150,/0/default.jpg

**Comment by TomDeneire** [comment]
Hi, 

thank for this very valid remark. In version 3 manifests I have indeed neglected the field "thumbnail" and used the first image instead. I've rectified this in this commit: https://github.com/TomDeneire/pictor/commit/49ae8c6bd227989aed1b39c8a9e98edd113b599c Of course, for the change to be apparant I would have to rebuild the whole database, which I'm definitely planning in the future, but haven't done just now.

Thanks again
