### ISSUE TITLE
Add manifests from Frick collection

### ISSUE THREAD

**Issue by alexander-winkler** [TomDeneire/pictor#33]
There is a IIIF endpoint for the NY Frick collection. Manifest URLs are  `https://collections.frick.org/apis/iiif/presentation/v2/objects-$i/manifest` for i = {0..}.

**Comment by TomDeneire** [comment]
API very slow, many pages not loading for whatever reason (e.g. https://collections.frick.org/apis/iiif/presentation/v2/objects-11/manifest), and only got to 29...

Harvested what I could. https://github.com/TomDeneire/pictor/commit/ece628f8a94abd7fc0e9fc22c39366c665c121e7
