### ISSUE TITLE
Add links to IIIF Viewers

### ISSUE THREAD

**Issue by glenrobson** [TomDeneire/pictor#4]
It would be nice as well as linking to the source manifest to also link to a viewer which can show the manifest.

See example links below for this `https://iiif-commons.github.io/fixtures/examples/av/multi-canvas/manifest.json`:

 * UniversalViewer: https://uv-v4.netlify.app/#?c=&m=&s=&cv=&manifest=https://iiif-commons.github.io/fixtures/examples/av/multi-canvas/manifest.json
 * Mirador: https://projectmirador.org/embed/?iiif-content=https://iiif-commons.github.io/fixtures/examples/av/multi-canvas/manifest.json
 * Clover: https://samvera-labs.github.io/clover-iiif/?iiif-content=https://iiif-commons.github.io/fixtures/examples/av/multi-canvas/manifest.json

**Comment by TomDeneire** [comment]
That's a great suggestion, which I've immediately implemented: https://github.com/TomDeneire/pictor/commit/83ce9a4539dda6e6a795ce15c9242bd5f45272b9
