### ISSUE TITLE
Getty SPARQL Query too restrictive

### ISSUE THREAD

**Issue by alexander-winkler** [TomDeneire/pictor#9]
`FILTER(CONTAINS(STR(?iiif),'iiif/manifest'))` in `harvester/getty.py` excludes `https://media.getty.edu/iiif/pres/...` manifest URLs.

It's better, I think, to use the following statement: `?iiif rdfs:label "IIIF Manifest URL" . ` (yields ca. 6,5k more results)

**Comment by TomDeneire** [comment]
Good call. Changed https://github.com/TomDeneire/pictor/commit/a2025185510f7198ad40410ecdd8c693129bbe1e
